import { NextRequest, NextResponse } from 'next/server'
import { ApiAccessError, requireApiAccess } from '@/lib/auth/api-access'
import { createDsarRequest, listDsarRequests, processDsar, verifyDsarIdentity } from '@/lib/privacy/dsar'

const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'private, no-store'}})
export const runtime='nodejs';export const dynamic='force-dynamic'

export async function GET(request:NextRequest){try{const access=await requireApiAccess({lane:'admin'});return json({ok:true,...await listDsarRequests(access,request.nextUrl.searchParams.get('workspaceId')||undefined)})}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);return json({ok:false,code:error instanceof Error?error.message.split(':')[0]:'privacy_dsar_list_failed'},500)}}
export async function POST(request:NextRequest){try{const access=await requireApiAccess({lane:'admin'});const body=await request.json();const result=await createDsarRequest(access,{workspaceId:body.workspaceId,subject:String(body.subject||''),channelHint:body.channelHint,requestType:body.requestType,requestPayload:body.requestPayload,dueAt:body.dueAt});return json({ok:true,request:result},201)}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);const code=error instanceof Error?error.message.split(':')[0]:'privacy_dsar_create_failed';return json({ok:false,code,error:'DSAR request was not created.'},code.includes('required')||code.includes('invalid')?400:500)}}
export async function PUT(request:NextRequest){try{const access=await requireApiAccess({lane:'admin'});const body=await request.json();const id=String(body.dsarRequestId||'');if(!id)return json({ok:false,code:'dsar_request_id_required'},400);if(body.action==='verify'){return json({ok:true,request:await verifyDsarIdentity(access,{dsarRequestId:id,verified:Boolean(body.verified),evidence:body.evidence})})}if(body.action==='process'){return json({ok:true,...await processDsar(access,{dsarRequestId:id})})}return json({ok:false,code:'unsupported_action'},400)}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);const code=error instanceof Error?error.message.split(':')[0]:'privacy_dsar_update_failed';const status=code.includes('identity_required')?409:code.includes('not_found')?404:500;return json({ok:false,code,error:'DSAR action was not completed.'},status)}}
