import type { ProviderCatalogEntry, ProviderKey } from './config-types';

export const providerCatalog: Record<ProviderKey, ProviderCatalogEntry> = {
  google_ads: {
    provider: 'google_ads',
    label: 'Google Ads',
    requiredKeys: [
      'GOOGLE_ADS_DEVELOPER_TOKEN',
      'GOOGLE_ADS_CLIENT_ID',
      'GOOGLE_ADS_CLIENT_SECRET',
      'GOOGLE_ADS_REFRESH_TOKEN',
      'GOOGLE_ADS_LOGIN_CUSTOMER_ID',
    ],
    optionalKeys: ['GOOGLE_ADS_CUSTOMER_ID'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['developer token', 'oauth credentials', 'manager account linkage'],
  },
  meta_marketing: {
    provider: 'meta_marketing',
    label: 'Meta Marketing',
    requiredKeys: [
      'META_APP_ID',
      'META_APP_SECRET',
      'META_SYSTEM_USER_TOKEN',
      'META_AD_ACCOUNT_ID',
      'META_PAGE_ID',
    ],
    optionalKeys: ['META_INSTAGRAM_ACCOUNT_ID'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['app review may be required', 'business verification may be required'],
  },
  linkedin_marketing: {
    provider: 'linkedin_marketing',
    label: 'LinkedIn Marketing',
    requiredKeys: [
      'LINKEDIN_CLIENT_ID',
      'LINKEDIN_CLIENT_SECRET',
      'LINKEDIN_ORGANIZATION_ID',
      'LINKEDIN_AD_ACCOUNT_ID',
    ],
    optionalKeys: ['LINKEDIN_REFRESH_TOKEN'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['approved product access may be required'],
  },
  youtube: {
    provider: 'youtube',
    label: 'YouTube',
    requiredKeys: [
      'YOUTUBE_CLIENT_ID',
      'YOUTUBE_CLIENT_SECRET',
      'YOUTUBE_REFRESH_TOKEN',
      'YOUTUBE_CHANNEL_ID',
    ],
    optionalKeys: [],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['upload scope', 'channel authorization'],
  },
  ga4: {
    provider: 'ga4',
    label: 'GA4',
    requiredKeys: [
      'GA4_PROPERTY_ID',
      'GA4_CLIENT_EMAIL',
      'GA4_PRIVATE_KEY',
    ],
    optionalKeys: ['GA4_MEASUREMENT_ID'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['property access required'],
  },
  search_console: {
    provider: 'search_console',
    label: 'Search Console',
    requiredKeys: [
      'GSC_SITE_URL',
      'GSC_CLIENT_EMAIL',
      'GSC_PRIVATE_KEY',
    ],
    optionalKeys: [],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['verified property access required'],
  },
  google_business_profile: {
    provider: 'google_business_profile',
    label: 'Google Business Profile',
    requiredKeys: [
      'GBP_ACCOUNT_ID',
      'GBP_LOCATION_ID',
      'GBP_CLIENT_ID',
      'GBP_CLIENT_SECRET',
      'GBP_REFRESH_TOKEN',
    ],
    optionalKeys: [],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['api access approval may be required'],
  },
  payment_gateway: {
    provider: 'payment_gateway',
    label: 'Payment Gateway',
    requiredKeys: [
      'PAYMENT_GATEWAY_PROVIDER',
      'PAYMENT_GATEWAY_KEY_ID',
      'PAYMENT_GATEWAY_KEY_SECRET',
      'PAYMENT_GATEWAY_WEBHOOK_SECRET',
    ],
    optionalKeys: ['PAYMENT_GATEWAY_ACCOUNT_ID'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['webhook secret is different from api key secret'],
  },
  esign: {
    provider: 'esign',
    label: 'eSign',
    requiredKeys: [
      'ESIGN_PROVIDER',
      'ESIGN_API_KEY',
      'ESIGN_WEBHOOK_SECRET',
    ],
    optionalKeys: ['ESIGN_ACCOUNT_ID'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['India-first recommendation: Leegality'],
  },
  whatsapp: {
    provider: 'whatsapp',
    label: 'WhatsApp',
    requiredKeys: [
      'WHATSAPP_ACCESS_TOKEN',
      'WHATSAPP_PHONE_NUMBER_ID',
      'WHATSAPP_BUSINESS_ACCOUNT_ID',
      'WHATSAPP_APP_SECRET',
    ],
    optionalKeys: ['WHATSAPP_VERIFY_TOKEN'],
    syncTargets: ['supabase_vault', 'vercel_env', 'runtime_adapter'],
    notes: ['business verification and templates may be required'],
  },
};