import { NextRequest, NextResponse } from 'next/server'
import { ApiAccessError, requireApiAccess } from '@/lib/auth/api-access'
import { createRetentionPolicy, listRetention, runRetention } from '@/lib/privacy/retention'

const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'private, no-store'}})
export const runtime='nodejs';export const dynamic='force-dynamic'

export async function GET(request:NextRequest){try{const access=await requireApiAccess({lane:'admin'});return json({ok:true,...await listRetention(access,request.nextUrl.searchParams.get('workspaceId')||undefined)})}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);return json({ok:false,code:error instanceof Error?error.message.split(':')[0]:'retention_list_failed'},500)}}
export async function POST(request:NextRequest){try{const access=await requireApiAccess({lane:'admin'});const body=await request.json();if(body.action==='create_policy'){const policy=await createRetentionPolicy(access,{workspaceId:body.workspaceId,dataClass:String(body.dataClass||''),targetTable:String(body.targetTable||''),retentionDays:Number(body.retentionDays||0),action:body.retentionAction||'review',legalBasis:body.legalBasis,enabled:body.enabled});return json({ok:true,policy},201)}if(body.action==='run'){const policyId=String(body.policyId||'');if(!policyId)return json({ok:false,code:'retention_policy_id_required'},400);return json({ok:true,...await runRetention(access,{policyId,mode:body.mode==='execute'?'execute':'dry_run',approvalId:body.approvalId})})}return json({ok:false,code:'unsupported_action'},400)}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);const code=error instanceof Error?error.message.split(':')[0]:'retention_action_failed';const status=code.includes('approval')?409:code.includes('protected')||code.includes('disabled')?409:code.includes('required')||code.includes('invalid')?400:500;return json({ok:false,code,error:'Retention action was not completed.'},status)}}
