'use client'

import { FormEvent, useState } from 'react'

const workspaceOptions=[{id:'workspace_oye_internal',label:'Oye !magine internal'},{id:'workspace_neejee',label:'Neejee pilot'}]

export default function AgentWorkspacePage(){
  const[workspaceId,setWorkspaceId]=useState('workspace_neejee');const[sourceTitle,setSourceTitle]=useState('Neejee brand evidence');const[sourceUri,setSourceUri]=useState('https://neejee.com');const[content,setContent]=useState('');const[query,setQuery]=useState('');const[objective,setObjective]=useState('');const[notice,setNotice]=useState('');const[citations,setCitations]=useState<any[]>([]);const[result,setResult]=useState<any>(null);const[busy,setBusy]=useState(false)
  async function ingest(event:FormEvent){event.preventDefault();setBusy(true);try{const r=await fetch('/api/admin/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,sourceType:'website',sourceUri,title:sourceTitle,content})});const j=await r.json();setNotice(j.ok?`Knowledge source stored as ${j.sourceId}; ${j.chunkCount} chunk(s), ${j.embeddingCount} embedded.`:`${j.code}: ${j.error||'Ingestion failed.'}`)}finally{setBusy(false)}}
  async function retrieve(){setBusy(true);try{const r=await fetch(`/api/admin/knowledge?workspaceId=${encodeURIComponent(workspaceId)}&q=${encodeURIComponent(query)}`,{cache:'no-store'});const j=await r.json();if(j.ok){setCitations(j.citations||[]);setNotice(`Retrieved ${(j.citations||[]).length} tenant-scoped evidence chunk(s).`)}else setNotice(`${j.code}: ${j.error||'Retrieval failed.'}`)}finally{setBusy(false)}}
  async function runAgent(){setBusy(true);try{const r=await fetch('/api/admin/agents/brand-strategist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,objective})});const j=await r.json();setResult(j.ok?j:null);setNotice(j.ok?`Draft strategy ${j.artifact?.artifact_id||''} created for human review.`:`${j.code}: ${j.error||'Agent run failed.'}`)}finally{setBusy(false)}}
  async function kill(value:boolean){const r=await fetch('/api/admin/agents/policy',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,agentKey:'brand-strategist',killSwitch:value})});const j=await r.json();setNotice(j.ok?`Brand Strategist kill switch ${value?'enabled':'released'}.`:`${j.code}: policy update failed.`)}
  return <main className="min-h-screen bg-[#111] px-6 py-10 text-[#fffdf8]"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-[#fdca5a]">Brand memory + bounded agents</p><h1 className="mt-3 text-4xl font-black tracking-[-0.05em]">Ground the agent before you let it draft.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/60">Sources, retrieval citations, tool traces, model cost and evaluation are persisted. This agent can read evidence and create a draft strategy only; it has no publish, spend, payment or messaging tool.</p></div><a href="/admin" className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold">Operator home</a></div>
  <div className="mt-8"><label className="text-xs font-black uppercase tracking-[0.18em] text-white/50">Workspace</label><select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)} className="ml-3 rounded-xl border border-white/15 bg-black px-4 py-3">{workspaceOptions.map(w=><option key={w.id} value={w.id}>{w.label}</option>)}</select></div>
  {notice?<p className="mt-5 rounded-xl bg-[#f7adc8] p-4 font-bold text-black">{notice}</p>:null}
  <section className="mt-8 grid gap-6 lg:grid-cols-2"><form onSubmit={ingest} className="rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><h2 className="text-xl font-black">Ingest approved evidence</h2><input value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)} className="mt-4 w-full rounded-xl border border-white/15 bg-black p-3" placeholder="Source title"/><input value={sourceUri} onChange={e=>setSourceUri(e.target.value)} className="mt-3 w-full rounded-xl border border-white/15 bg-black p-3" placeholder="Source URL or reference"/><textarea rows={12} value={content} onChange={e=>setContent(e.target.value)} className="mt-3 w-full rounded-xl border border-white/15 bg-black p-3" placeholder="Paste the approved source content to ingest. Website crawling can feed this same controlled ingestion layer."/><button disabled={busy||!content.trim()} className="mt-4 w-full rounded-full bg-[#fdca5a] px-5 py-3 font-black text-black disabled:opacity-50">Store brand evidence</button></form>
  <div className="rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><h2 className="text-xl font-black">Retrieve with citations</h2><textarea rows={4} value={query} onChange={e=>setQuery(e.target.value)} className="mt-4 w-full rounded-xl border border-white/15 bg-black p-3" placeholder="What evidence should the operating system retrieve?"/><button disabled={busy||!query.trim()} onClick={()=>void retrieve()} className="mt-3 rounded-full bg-[#f7adc8] px-5 py-3 font-black text-black disabled:opacity-50">Retrieve</button><div className="mt-5 grid gap-3">{citations.map((c,i)=><article key={c.chunkId} className="rounded-xl border border-white/10 bg-black/30 p-4"><p className="font-black">[S{i+1}] {c.sourceTitle}</p><p className="mt-1 text-xs text-white/45">{c.version} · {c.freshness} · {c.sourceUri||'internal source'}</p><p className="mt-3 max-h-36 overflow-auto text-sm leading-6 text-white/70">{c.content}</p></article>)}</div></div></section>
  <section className="mt-6 rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Bounded Brand Strategist</h2><div className="flex gap-2"><button onClick={()=>void kill(true)} className="rounded-full border border-red-400 px-3 py-2 text-xs font-black text-red-300">Kill agent</button><button onClick={()=>void kill(false)} className="rounded-full border border-emerald-400 px-3 py-2 text-xs font-black text-emerald-300">Release kill switch</button></div></div><textarea rows={5} value={objective} onChange={e=>setObjective(e.target.value)} className="mt-4 w-full rounded-xl border border-white/15 bg-black p-3" placeholder="Strategy objective"/><button disabled={busy||!objective.trim()} onClick={()=>void runAgent()} className="mt-3 rounded-full bg-[#fdca5a] px-5 py-3 font-black text-black disabled:opacity-50">Run grounded draft agent</button>{result?<div className="mt-5 grid gap-4 lg:grid-cols-[1fr_0.35fr]"><pre className="whitespace-pre-wrap rounded-xl bg-black/40 p-5 text-sm leading-7 text-white/75">{result.draft}</pre><aside className="rounded-xl border border-white/10 bg-black/30 p-4"><p className="font-black">Evaluation</p><p className="mt-2 text-sm">Score: {result.evaluation?.score}</p><p className="mt-1 text-sm">Citation coverage: {result.evaluation?.citationCoverage}</p><p className="mt-3 text-xs text-amber-300">Human approval remains required.</p></aside></div>:null}</section>
  </section></main>
}
