import type { Route } from 'next'
import Link from 'next/link'
import { formatInr, getPublishedPricingCatalog } from '@/lib/public/pricing-runtime'
import { buildMetadata } from '@/lib/seo/site'

export const metadata = buildMetadata('/pricing','Commercial model','Oye !magine commercial models for platform access, marketplace delivery, managed growth and enterprise operating environments.')

function priceHeadline(plan: Awaited<ReturnType<typeof getPublishedPricingCatalog>>['plans'][number]) {
  if (plan.price_mode === 'custom') return 'Structured scope'
  const prefix = plan.price_mode === 'from' ? 'From ' : ''
  return `${prefix}${formatInr(plan.monthly_price_inr)}`
}

export default async function PricingPage() {
  const { plans, policy } = await getPublishedPricingCatalog()
  const policyItems = Object.values(policy.policy_copy ?? {}).filter((value): value is string => typeof value === 'string' && Boolean(value.trim()))
  return (
    <main className="public-premium">
      <section className="commercial-hero"><div className="public-wrap"><p className="public-kicker">Commercial model</p><h1>Choose the operating depth. Keep the economics explicit.</h1><p>Oye !magine separates platform access, specialist delivery, external media and contracted pass-through costs. Teams can begin with the operating system, add marketplace capacity when required, or structure a managed-growth or enterprise engagement around a broader mandate.</p><div className="public-actions"><Link href="/contact" className="public-btn-primary">Discuss the right structure <span>↗</span></Link><Link href="/marketplace" className="public-btn-secondary">Explore marketplace delivery</Link></div></div></section>
      <section className="public-section"><div className="public-wrap"><div className="public-section-head"><p className="public-kicker">Published platform editions</p><div><h2>Commercial clarity before activation.</h2><p>Where a published subscription price exists, it is shown below from the governed commercial catalogue. Tailored editions are scoped against operating complexity, governance and contracted delivery requirements.</p></div></div><div className="commercial-plan-grid">{plans.map((plan,index)=><article className={`commercial-plan ${plan.featured?'featured':''}`} key={plan.plan_key}><small>{String(index+1).padStart(2,'0')} · {plan.support_tier}</small><h2>{plan.display_name}</h2><p>{plan.audience}</p><div className="commercial-price"><strong>{priceHeadline(plan)}</strong><span>{plan.price_mode==='custom'?'Commercial terms follow agreed scope':'per month · platform subscription · '+policy.tax_label}</span></div><ul>{plan.highlights.slice(0,6).map(item=><li key={item}>— {item}</li>)}</ul><Link href={plan.cta_href as Route}><span>{plan.price_mode==='custom'?'Discuss scope':plan.cta_label}</span><span>↗</span></Link></article>)}</div></div></section>
      <section className="public-section dark"><div className="public-wrap"><div className="public-section-head"><p className="public-kicker">What remains separate</p><div><h2>The platform is not a disguised media wallet.</h2><p>Media budgets, external provider charges and specialist marketplace delivery are commercially distinct from the platform subscription unless a signed scope states otherwise. High-impact spend and publishing remain approval-bound.</p></div></div><div className="public-proof"><div><span>Platform</span><strong>Software & operating intelligence</strong><p>Workspace, AI, workflow, governance and included modules.</p></div><div><span>Marketplace</span><strong>Scoped specialist outcomes</strong><p>Defined briefs and delivery commitments.</p></div><div><span>External spend</span><strong>Client-funded and traceable</strong><p>Media and provider costs remain separately visible.</p></div><div><span>Enterprise</span><strong>Contracted operating model</strong><p>Governance, scale, integrations and managed services by scope.</p></div></div></div></section>
      <section className="public-section soft"><div className="public-wrap"><div className="public-section-head"><p className="public-kicker">Commercial policy</p><div><h2>Terms that can be understood before the work begins.</h2><p>{policy.annual_savings_label}. Pricing, taxes, fair-use rules and external charges are governed by the published catalogue and the applicable order or engagement document.</p></div></div><div className="public-card-grid">{policyItems.slice(0,6).map((item,index)=><article className="public-card" key={item}><span className="public-card-number">{String(index+1).padStart(2,'0')}</span><h3>{item}</h3></article>)}</div></div></section>
      <section className="public-final"><div className="public-wrap public-final-grid"><div><p className="public-kicker">Enterprise, managed growth or a defined capability</p><h2>Structure the engagement around the business problem, not a forced package.</h2></div><div><p>Share the operating objective, current stack, team structure and required level of delivery. Oye !magine will map the commercial model and the governance required around it.</p><div className="public-actions"><Link href="/contact" className="public-btn-primary">Discuss an engagement <span>↗</span></Link></div></div></div></section>
    </main>
  )
}
