'use client'

import { FormEvent, useEffect, useState } from 'react'

type Workspace={id:string;name:string;slug:string;brands?:{name?:string};tenants?:{display_name?:string;slug?:string}}

export default function PrivacyAdminPage(){
 const[workspaces,setWorkspaces]=useState<Workspace[]>([]),[workspaceId,setWorkspaceId]=useState(''),[notice,setNotice]=useState(''),[privacy,setPrivacy]=useState<any>(null),[dsars,setDsars]=useState<any[]>([]),[retention,setRetention]=useState<any>(null),[busy,setBusy]=useState(false)
 const[subject,setSubject]=useState(''),[channel,setChannel]=useState<'email'|'whatsapp'|'sms'>('email'),[purpose,setPurpose]=useState('marketing'),[decision,setDecision]=useState<'granted'|'withdrawn'>('granted')
 const[dsarType,setDsarType]=useState('access'),[targetTable,setTargetTable]=useState('raw_growth_events'),[retentionDays,setRetentionDays]=useState(90),[deliveryMessage,setDeliveryMessage]=useState('')
 useEffect(()=>{void fetch('/api/admin/privacy/targets',{cache:'no-store'}).then(r=>r.json()).then(j=>{if(j.ok){setWorkspaces(j.workspaces||[]);const n=(j.workspaces||[]).find((w:any)=>String(w.slug).includes('neejee')||String(w.brands?.name||'').toLowerCase()==='neejee');setWorkspaceId((n||j.workspaces?.[0])?.id||'')}})},[])
 useEffect(()=>{if(workspaceId)void refresh()},[workspaceId])
 async function refresh(){const q=`?workspaceId=${encodeURIComponent(workspaceId)}`;const[a,b,c]=await Promise.all([fetch('/api/admin/privacy/consent'+q,{cache:'no-store'}).then(r=>r.json()),fetch('/api/admin/privacy/dsar'+q,{cache:'no-store'}).then(r=>r.json()),fetch('/api/admin/privacy/retention'+q,{cache:'no-store'}).then(r=>r.json())]);if(a.ok)setPrivacy(a);if(b.ok)setDsars(b.requests||[]);if(c.ok)setRetention(c)}
 async function recordConsent(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/admin/privacy/consent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,subject,channel,purpose,decision,noticeVersion:'operator-v1',source:'operator_ui'})});const j=await r.json();setNotice(j.ok?'Consent event recorded.':`${j.code}: ${j.error||'Consent failed.'}`);if(j.ok)await refresh()}finally{setBusy(false)}}
 async function suppress(){setBusy(true);try{const r=await fetch('/api/admin/privacy/suppressions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,subject,channel,scope:'channel',reason:'operator_request',source:'operator_ui'})});const j=await r.json();setNotice(j.ok?'Channel suppression recorded.':`${j.code}: ${j.error||'Suppression failed.'}`);if(j.ok)await refresh()}finally{setBusy(false)}}
 async function createDsar(){setBusy(true);try{const r=await fetch('/api/admin/privacy/dsar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,subject,channelHint:channel,requestType:dsarType})});const j=await r.json();setNotice(j.ok?`DSAR ${j.request.dsar_request_id} created. Verify identity before processing.`:`${j.code}: ${j.error||'DSAR failed.'}`);if(j.ok)await refresh()}finally{setBusy(false)}}
 async function dsarAction(id:string,action:'verify'|'process'){setBusy(true);try{const r=await fetch('/api/admin/privacy/dsar',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({dsarRequestId:id,action,...(action==='verify'?{verified:true,evidence:{method:'operator_verified'}}:{})})});const j=await r.json();setNotice(j.ok?`${action==='verify'?'Identity verified':'DSAR processed'} for ${id}.`:`${j.code}: ${j.error||'DSAR action failed.'}`);if(j.ok)await refresh()}finally{setBusy(false)}}
 async function createRetention(){setBusy(true);try{const r=await fetch('/api/admin/privacy/retention',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create_policy',workspaceId,dataClass:'operational_ephemeral',targetTable,retentionDays,retentionAction:'delete',legalBasis:'documented operational retention policy'})});const j=await r.json();setNotice(j.ok?`Retention policy ${j.policy.retention_policy_id} created.`:`${j.code}: ${j.error||'Policy failed.'}`);if(j.ok)await refresh()}finally{setBusy(false)}}
 async function dryRun(policyId:string){const r=await fetch('/api/admin/privacy/retention',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'run',policyId,mode:'dry_run'})});const j=await r.json();setNotice(j.ok?`Dry run: ${j.candidateCount} candidate record(s), no deletion performed.`:`${j.code}: ${j.error||'Dry run failed.'}`);if(j.ok)await refresh()}
 async function sendTest(){setBusy(true);try{const payload:any={workspaceId,channel,purpose,subject};if(channel==='email')payload.email={subject:'Oye !magine lifecycle test',text:deliveryMessage||'Lifecycle test'};if(channel==='whatsapp')payload.whatsapp={templateName:deliveryMessage||'hello_world',languageCode:'en_US'};if(channel==='sms')payload.sms={message:deliveryMessage||'Oye Imagine lifecycle test'};const r=await fetch('/api/admin/lifecycle/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setNotice(j.ok?(j.blocked?`Blocked correctly: ${j.reason}`:`Provider accepted message ${j.providerMessageId||''}.`):`${j.code}: ${j.error||'Send failed.'}`);if(j.ok)await refresh()}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#111] px-6 py-10 text-[#fffdf8]"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#fdca5a]">Privacy & lifecycle control plane</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Consent before delivery. Evidence before deletion.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/60">Every lifecycle send is checked against the current consent and suppression ledger. DSAR identity is verified before export. Retention executes only on an allowlisted ephemeral table and only after an approval explicitly scoped to that policy.</p></div><a href="/admin" className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold">Operator home</a></div>
 <div className="mt-8 rounded-[2rem] border border-white/15 bg-white/[.06] p-6"><label className="text-xs font-black uppercase tracking-[.18em] text-white/50">Workspace</label><select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)} className="ml-3 rounded-xl border border-white/15 bg-black px-4 py-3">{workspaces.map(w=><option key={w.id} value={w.id}>{w.brands?.name||w.name} · {w.tenants?.display_name||w.tenants?.slug}</option>)}</select></div>
 {notice?<p className="mt-5 rounded-xl bg-[#f7adc8] p-4 font-bold text-black">{notice}</p>:null}
 <section className="mt-6 grid gap-6 xl:grid-cols-2"><form onSubmit={recordConsent} className="rounded-[2rem] border border-white/15 bg-white/[.06] p-6"><h2 className="text-xl font-black">Consent & suppression</h2><input value={subject} onChange={e=>setSubject(e.target.value)} className="mt-4 w-full rounded-xl border border-white/15 bg-black p-3" placeholder="Email or phone subject"/><div className="mt-3 grid grid-cols-3 gap-3"><select value={channel} onChange={e=>setChannel(e.target.value as any)} className="rounded-xl border border-white/15 bg-black p-3"><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option></select><input value={purpose} onChange={e=>setPurpose(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3"/><select value={decision} onChange={e=>setDecision(e.target.value as any)} className="rounded-xl border border-white/15 bg-black p-3"><option value="granted">Granted</option><option value="withdrawn">Withdrawn</option></select></div><div className="mt-4 flex gap-3"><button disabled={busy||!subject} className="rounded-full bg-[#fdca5a] px-5 py-3 font-black text-black disabled:opacity-50">Record consent event</button><button type="button" disabled={busy||!subject} onClick={()=>void suppress()} className="rounded-full border border-red-400 px-5 py-3 font-black text-red-300 disabled:opacity-50">Suppress channel</button></div><div className="mt-5 max-h-56 overflow-auto text-xs text-white/55">{(privacy?.consents||[]).slice(0,12).map((c:any)=><p key={c.consent_event_id} className="border-t border-white/10 py-2">{c.subject_key} · {c.channel}/{c.purpose} · {c.decision} · {new Date(c.occurred_at).toLocaleString()}</p>)}</div></form>
 <div className="rounded-[2rem] border border-white/15 bg-white/[.06] p-6"><h2 className="text-xl font-black">Consent-enforced delivery</h2><p className="mt-2 text-sm text-white/50">Uses the same subject, channel and purpose above. Missing consent or an active suppression creates a blocked job and never calls the provider.</p><textarea rows={4} value={deliveryMessage} onChange={e=>setDeliveryMessage(e.target.value)} className="mt-4 w-full rounded-xl border border-white/15 bg-black p-3" placeholder={channel==='whatsapp'?'Approved WhatsApp template name':'Message/body'}/><button disabled={busy||!subject} onClick={()=>void sendTest()} className="mt-4 rounded-full bg-[#f7adc8] px-5 py-3 font-black text-black disabled:opacity-50">Attempt governed send</button></div>
 <div className="rounded-[2rem] border border-white/15 bg-white/[.06] p-6"><h2 className="text-xl font-black">DSAR</h2><div className="mt-4 flex gap-3"><select value={dsarType} onChange={e=>setDsarType(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3"><option value="access">Access</option><option value="export">Export</option><option value="correction">Correction</option><option value="deletion">Deletion</option><option value="restriction">Restriction</option><option value="objection">Objection</option></select><button disabled={busy||!subject} onClick={()=>void createDsar()} className="rounded-full bg-[#fdca5a] px-5 py-3 font-black text-black disabled:opacity-50">Create request</button></div><div className="mt-5 grid gap-3">{dsars.slice(0,8).map((d:any)=><article key={d.dsar_request_id} className="rounded-xl border border-white/10 bg-black/30 p-4"><p className="font-black">{d.request_type} · {d.status}</p><p className="mt-1 text-xs text-white/45">{d.subject_key} · identity {d.identity_status}</p><div className="mt-3 flex gap-2"><button onClick={()=>void dsarAction(d.dsar_request_id,'verify')} className="rounded-full border border-white/20 px-3 py-2 text-xs font-bold">Verify identity</button><button onClick={()=>void dsarAction(d.dsar_request_id,'process')} className="rounded-full border border-white/20 px-3 py-2 text-xs font-bold">Process</button></div></article>)}</div></div>
 <div className="rounded-[2rem] border border-white/15 bg-white/[.06] p-6"><h2 className="text-xl font-black">Retention</h2><div className="mt-4 grid grid-cols-[1fr_.5fr_auto] gap-3"><select value={targetTable} onChange={e=>setTargetTable(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3">{(retention?.deletableTargets||['raw_growth_events','integration_sync_runs','lifecycle_delivery_jobs']).map((t:string)=><option key={t}>{t}</option>)}</select><input type="number" min={1} value={retentionDays} onChange={e=>setRetentionDays(Number(e.target.value))} className="rounded-xl border border-white/15 bg-black p-3"/><button onClick={()=>void createRetention()} className="rounded-full bg-[#fdca5a] px-4 py-2 font-black text-black">Create</button></div><p className="mt-3 text-xs text-white/45">Execution is not offered here without an explicitly approved retention request. Dry runs never delete.</p><div className="mt-4 grid gap-2">{(retention?.policies||[]).slice(0,8).map((p:any)=><div key={p.retention_policy_id} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/30 p-3 text-sm"><span>{p.target_table} · {p.retention_days} days · {p.action}</span><button onClick={()=>void dryRun(p.retention_policy_id)} className="rounded-full border border-white/20 px-3 py-1 text-xs font-bold">Dry run</button></div>)}</div></div></section>
 </section></main>
}
