import Link from 'next/link'
import { neejeePilot } from '@/lib/public/product-catalog'
import { buildMetadata } from '@/lib/seo/site'

export const metadata = buildMetadata('/customers/neejee', 'Neejee Pilot', 'See the controlled Neejee commerce pilot architecture used to prove Oye !magine without fabricated healthcare or performance assumptions.')

export default function NeejeeCustomerPage() {
  return <div className="oi-page"><section className="oi-container">
    <header className="grid gap-6 rounded-[2.25rem] border-2 border-black bg-[var(--oye-paper)] p-7 shadow-[8px_8px_0_#111] md:p-10 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="text-xs font-black uppercase tracking-[0.24em]">Controlled reference pilot</p><h1 className="mt-4 text-5xl font-black leading-[0.95] tracking-[-0.06em] text-black md:text-7xl">{neejeePilot.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#4d4841]">{neejeePilot.intro}</p></div><aside className="rounded-[2rem] border-2 border-black bg-[var(--oye-pink)] p-6"><p className="text-xs font-black uppercase tracking-[0.2em]">Canonical business truth</p><ul className="mt-5 grid gap-3">{neejeePilot.truths.map((item)=><li key={item} className="rounded-xl border border-black/25 bg-white/40 px-4 py-3 text-sm font-bold leading-6">{item}</li>)}</ul></aside></header>

    <section className="mt-10 rounded-[2rem] border-2 border-black bg-black p-7 text-white md:p-9"><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--oye-yellow)]">The proving loop</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{neejeePilot.proofLoop.map((step,index)=><div key={step} className="rounded-xl border border-white/15 bg-white/10 p-4"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-black text-black ${index%2?'bg-[var(--oye-pink)]':'bg-[var(--oye-yellow)]'}`}>{index+1}</span><p className="mt-3 text-sm font-black leading-6">{step}</p></div>)}</div></section>

    <section className="mt-10 grid gap-5 lg:grid-cols-3"><article className="rounded-[2rem] border-2 border-black bg-[var(--oye-yellow)] p-7"><p className="text-xs font-black uppercase tracking-[0.2em]">Corrected truth layer</p><h2 className="mt-3 text-2xl font-black">No healthcare or generic B2B funnel assumptions.</h2><p className="mt-4 text-sm leading-7 text-[#39352f]">Pilot strategy, landing, paid-search, lifecycle and execution defaults are regression-tested against the commerce/craft truth contract.</p></article><article className="rounded-[2rem] border-2 border-black bg-[var(--oye-pink)] p-7"><p className="text-xs font-black uppercase tracking-[0.2em]">Private content layer</p><h2 className="mt-3 text-2xl font-black">Neejee has its own private asset bucket.</h2><p className="mt-4 text-sm leading-7 text-[#39352f]">Source and generated assets remain separated from Oye !magine corporate assets, with versions, rights, provider provenance and approvals.</p></article><article className="rounded-[2rem] border-2 border-black bg-[var(--oye-paper)] p-7"><p className="text-xs font-black uppercase tracking-[0.2em]">Execution truth</p><h2 className="mt-3 text-2xl font-black">External performance is not fabricated.</h2><p className="mt-4 text-sm leading-7 text-[#39352f]">Provider connection, campaign IDs, spend, commerce results and closed-loop optimization become proof only after the corresponding external systems are genuinely connected.</p></article></section>

    <section className="mt-10 rounded-[2rem] border-2 border-black bg-[var(--oye-paper)] p-7 md:p-9"><p className="text-sm leading-7 text-[#4d4841]">{neejeePilot.disclosure}</p><div className="mt-5 flex flex-wrap gap-3"><a href="https://neejee.com" className="rounded-full border-2 border-black bg-black px-5 py-3 font-black text-white" rel="noreferrer">Visit Neejee</a><Link href="/contact" className="rounded-full border-2 border-black bg-[var(--oye-yellow)] px-5 py-3 font-black text-black">Discuss a pilot</Link></div></section>
  </section></div>
}
