import type { ProviderKey, ProviderRequirement } from './activation-types';

export const providerRequirements: Record<ProviderKey, ProviderRequirement> = {
  google_ads: {
    provider: 'google_ads',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: false,
    requiresLiveAccount: true,
    notes: ['developer token', 'production access level', 'manager account linkage'],
  },
  meta_marketing: {
    provider: 'meta_marketing',
    requiresCredentials: true,
    requiresAppReview: true,
    requiresBusinessVerification: true,
    requiresLiveAccount: true,
    notes: ['app review', 'business verification', 'ad account and page access'],
  },
  linkedin_marketing: {
    provider: 'linkedin_marketing',
    requiresCredentials: true,
    requiresAppReview: true,
    requiresBusinessVerification: false,
    requiresLiveAccount: true,
    notes: ['approved marketing access', 'organisation permissions'],
  },
  youtube: {
    provider: 'youtube',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: false,
    requiresLiveAccount: true,
    notes: ['oauth scopes', 'channel auth', 'upload verification'],
  },
  ga4: {
    provider: 'ga4',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: false,
    requiresLiveAccount: true,
    notes: ['property access', 'report validation'],
  },
  search_console: {
    provider: 'search_console',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: false,
    requiresLiveAccount: true,
    notes: ['verified property access', 'quota-aware ingestion'],
  },
  google_business_profile: {
    provider: 'google_business_profile',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: false,
    requiresLiveAccount: true,
    notes: ['profile ownership', 'api access approval if applicable'],
  },
  payment_gateway: {
    provider: 'payment_gateway',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: true,
    requiresLiveAccount: true,
    notes: ['merchant setup', 'live webhooks', 'refund and reconciliation flow'],
  },
  esign: {
    provider: 'esign',
    requiresCredentials: true,
    requiresAppReview: false,
    requiresBusinessVerification: true,
    requiresLiveAccount: true,
    notes: ['production agreement', 'signing evidence validation'],
  },
  whatsapp: {
    provider: 'whatsapp',
    requiresCredentials: true,
    requiresAppReview: true,
    requiresBusinessVerification: true,
    requiresLiveAccount: true,
    notes: ['business verification', 'template approval', 'number onboarding'],
  },
};