'use client'
import { useEffect, useMemo, useState } from 'react'

type Workspace={id:string;name:string;slug:string;tenant_id:string;brands?:{name?:string};tenants?:{slug?:string;display_name?:string}}

export default function IntegrationsAdminPage(){
 const[workspaces,setWorkspaces]=useState<Workspace[]>([]);const[workspaceId,setWorkspaceId]=useState('');const[notice,setNotice]=useState('');const[discovery,setDiscovery]=useState<any>(null);const[health,setHealth]=useState<any>(null);const[busy,setBusy]=useState(false);const[customerId,setCustomerId]=useState('');const[propertyId,setPropertyId]=useState('');const[siteUrl,setSiteUrl]=useState('https://neejee.com/');const[startDate,setStartDate]=useState(()=>new Date(Date.now()-7*86400000).toISOString().slice(0,10));const[endDate,setEndDate]=useState(()=>new Date().toISOString().slice(0,10))
 useEffect(()=>{void fetch('/api/admin/integrations/targets',{cache:'no-store'}).then(r=>r.json()).then(j=>{if(j.ok){setWorkspaces(j.workspaces||[]);const neejee=(j.workspaces||[]).find((w:any)=>String(w.slug).includes('neejee')||String(w.brands?.name||'').toLowerCase()==='neejee');setWorkspaceId((neejee||j.workspaces?.[0])?.id||'')}})},[])
 const selected=useMemo(()=>workspaces.find(w=>w.id===workspaceId),[workspaces,workspaceId])
 async function connect(){setBusy(true);try{const r=await fetch(`/api/admin/integrations/google/start?workspaceId=${encodeURIComponent(workspaceId)}`,{cache:'no-store'});const j=await r.json();if(j.ok&&j.authorizationUrl)window.location.href=j.authorizationUrl;else setNotice(`${j.code}: ${j.error||'Google OAuth not configured.'}`)}finally{setBusy(false)}}
 async function discover(){setBusy(true);try{const r=await fetch(`/api/admin/integrations/google/discover?workspaceId=${encodeURIComponent(workspaceId)}`,{cache:'no-store'});const j=await r.json();if(j.ok){setDiscovery(j);setNotice('Google resources discovered. Select the appropriate account/property/site before syncing.')}else setNotice(`${j.code}: ${j.error||'Discovery failed.'}`)}finally{setBusy(false)}}
 async function sync(provider:string){setBusy(true);try{const body:any={workspaceId,provider,startDate,endDate};if(provider==='google_ads')body.customerId=customerId;if(provider==='ga4')body.propertyId=propertyId;if(provider==='gsc')body.siteUrl=siteUrl;const r=await fetch('/api/admin/integrations/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setNotice(j.ok?`${provider} sync completed: ${j.rowsWritten} row(s) normalized.`:`${j.code}: ${j.error||'Sync failed.'}`);if(j.ok)await loadHealth()}finally{setBusy(false)}}
 async function loadHealth(){const r=await fetch(`/api/admin/integrations/health?workspaceId=${encodeURIComponent(workspaceId)}`,{cache:'no-store'});const j=await r.json();if(j.ok)setHealth(j)}
 async function recommend(){setBusy(true);try{const r=await fetch('/api/admin/integrations/health',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,startDate,endDate})});const j=await r.json();setNotice(j.ok?`${j.recommendation} No provider mutation was performed.`:`${j.code}: recommendation failed.`)}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#111] px-6 py-10 text-[#fffdf8]"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-[#fdca5a]">Integrations & data truth</p><h1 className="mt-3 text-4xl font-black tracking-[-0.05em]">Connect. Discover. Read. Reconcile.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/60">Provider capability stays separate from a tenant-specific connection. OAuth tokens are encrypted server-side; the UI receives resource metadata and evidence states, never secrets.</p></div><a href="/admin" className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold">Operator home</a></div>
 <section className="mt-8 rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><label className="text-xs font-black uppercase tracking-[0.18em] text-white/50">Operational workspace</label><select value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)} className="ml-3 rounded-xl border border-white/15 bg-black px-4 py-3">{workspaces.map(w=><option key={w.id} value={w.id}>{w.brands?.name||w.name} · {w.tenants?.display_name||w.tenants?.slug}</option>)}</select><p className="mt-3 text-xs text-white/45">Selected: {selected?.name||'none'} · {workspaceId||'no workspace'}</p></section>
 {notice?<p className="mt-5 rounded-xl bg-[#f7adc8] p-4 font-bold text-black">{notice}</p>:null}
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><h2 className="text-xl font-black">Google connection</h2><p className="mt-3 text-sm leading-6 text-white/55">OAuth requests Ads, Analytics and Search Console read scopes. Google Ads writes remain approval-bound and create PAUSED campaigns only.</p><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy||!workspaceId} onClick={()=>void connect()} className="rounded-full bg-[#fdca5a] px-5 py-3 font-black text-black disabled:opacity-50">Connect Google</button><button disabled={busy||!workspaceId} onClick={()=>void discover()} className="rounded-full bg-[#f7adc8] px-5 py-3 font-black text-black disabled:opacity-50">Discover resources</button></div>{discovery?<pre className="mt-5 max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-black/40 p-4 text-xs text-white/65">{JSON.stringify({googleAds:discovery.googleAds?.data,ga4:discovery.ga4?.data,searchConsole:discovery.searchConsole?.data},null,2)}</pre>:null}</article>
 <article className="rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><h2 className="text-xl font-black">Source sync</h2><div className="mt-4 grid gap-3"><div className="grid grid-cols-2 gap-3"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3"/><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3"/></div><input value={customerId} onChange={e=>setCustomerId(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3" placeholder="Google Ads customer ID"/><button disabled={busy||!customerId} onClick={()=>void sync('google_ads')} className="rounded-full border border-white/20 px-4 py-2 font-bold">Sync Google Ads</button><input value={propertyId} onChange={e=>setPropertyId(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3" placeholder="GA4 property ID"/><button disabled={busy||!propertyId} onClick={()=>void sync('ga4')} className="rounded-full border border-white/20 px-4 py-2 font-bold">Sync GA4</button><input value={siteUrl} onChange={e=>setSiteUrl(e.target.value)} className="rounded-xl border border-white/15 bg-black p-3" placeholder="Search Console property URL"/><button disabled={busy||!siteUrl} onClick={()=>void sync('gsc')} className="rounded-full border border-white/20 px-4 py-2 font-bold">Sync Search Console</button></div></article></section>
 <section className="mt-6 rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Freshness & recommendation</h2><div className="flex gap-2"><button onClick={()=>void loadHealth()} className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold">Refresh freshness</button><button onClick={()=>void recommend()} className="rounded-full bg-[#fdca5a] px-4 py-2 text-sm font-black text-black">Generate guarded recommendation</button></div></div>{health?<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{health.sources.map((s:any)=><div key={s.provider} className="rounded-xl border border-white/10 bg-black/30 p-4"><p className="font-black">{s.provider}</p><p className="mt-1 text-sm text-white/60">{s.state}</p><p className="mt-2 text-xs text-white/40">{s.freshnessAt||'No authoritative sync yet'}</p></div>)}</div>:<p className="mt-4 text-sm text-white/45">Load freshness to distinguish no data, stale data and provider errors.</p>}</section>
 </section></main>
}
