import { NextRequest, NextResponse } from 'next/server'
import { ApiAccessError, requireApiAccess } from '@/lib/auth/api-access'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'

const states=['code_capability','configured','connected','read_verified','sandbox_executed','production_executed'] as const
function json(body:unknown,status=200){return NextResponse.json(body,{status,headers:{'Cache-Control':'private, no-store'}})}

export async function GET(){try{await requireApiAccess({lane:'admin'});const admin=createSupabaseAdminClient();const{data,error}=await admin.from('cms_claims_register').select('*').order('claim_key');if(error)throw error;return json({ok:true,claims:data??[]})}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);return json({ok:false,code:'claims_read_failed'},500)}}

export async function PUT(request:NextRequest){try{const access=await requireApiAccess({lane:'admin'});const body=await request.json();const claimKey=String(body?.claimKey||'').trim();const currentState=String(body?.currentState||'').trim();if(!claimKey||!states.includes(currentState as any))return json({ok:false,code:'invalid_request'},400);const admin=createSupabaseAdminClient();const patch:any={current_state:currentState,evidence_refs:Array.isArray(body?.evidenceRefs)?body.evidenceRefs:[],notes:typeof body?.notes==='string'?body.notes:null,updated_at:new Date().toISOString()};if(body?.approve===true){patch.approved_by=access.email||access.subject;patch.approved_at=new Date().toISOString()}else if(body?.approve===false){patch.approved_by=null;patch.approved_at=null}const{data,error}=await admin.from('cms_claims_register').update(patch).eq('claim_key',claimKey).select('*').single();if(error)throw error;await admin.from('cms_audit_events').insert({entity_type:'claim',entity_slug:claimKey,action:'claim_evidence_updated',actor:access.email||access.subject,details:{currentState,approved:Boolean(patch.approved_at)}});return json({ok:true,claim:data})}catch(error){if(error instanceof ApiAccessError)return json({ok:false,code:error.code},error.status);return json({ok:false,code:'claims_write_failed'},500)}}
