import type {ConciergeResource,ConciergeScope} from './concierge-retrieval-types'
const T='tenant_oye_imagine',W='workspace_growth_os',B='brand_oye_imagine',O='tenant_other_brand'
const cd=['client_dashboard','help_panel','support_center'] as const
const mp=['marketplace_surface','help_panel','support_center'] as const
const sh=['client_dashboard','marketplace_surface','help_panel','support_center'] as const
const r=(x:ConciergeResource)=>x

export function buildPublicSupportConciergeScope():ConciergeScope{return{actorId:'anonymous',tenantId:'global',audience:'client',permissions:[]}}
export function buildPublicMarketplaceConciergeScope():ConciergeScope{return{actorId:'anonymous',tenantId:'global',audience:'marketplace_client',permissions:[]}}
export function buildDemoClientConciergeScope():ConciergeScope{return{actorId:'client_user_001',tenantId:T,workspaceId:W,brandId:B,audience:'client',permissions:['view_client_finance','view_client_agreements','view_client_reports','view_client_support','view_client_marketplace_documents']}}
export function buildDemoMarketplaceConciergeScope():ConciergeScope{return{actorId:'marketplace_user_001',tenantId:T,workspaceId:W,brandId:B,audience:'marketplace_client',permissions:['view_marketplace_requests','view_marketplace_proposals','view_marketplace_documents','view_marketplace_help']}}
export function buildDemoAdminConciergeScope():ConciergeScope{return{actorId:'admin_user_001',tenantId:T,workspaceId:W,brandId:B,audience:'admin',permissions:['view_admin_financials','view_internal_notes','view_concierge_audits','view_marketplace_requests']}}

export const conciergeResources:ConciergeResource[]=[
r({id:'help-services',kind:'help_article',title:'Services on offer',summary:'Growth strategy, paid media, SEO, analytics, CRO, content ops, CRM automations, specialist marketplace support, and premium reporting.',href:'/marketplace',tenantId:'global',visibility:'shared',audiences:['client','marketplace_client','admin'],surfaces:[...sh],tags:['services','offers','lanes'],keywords:['services on offer','service lanes','marketplace services'],status:'published',links:[{label:'Open services',href:'/marketplace'}]}),
r({id:'help-support',kind:'help_article',title:'Support contact and escalation',summary:'Contact support via the support center or hello@oyeimagine.com. Priority issues route to support operations.',href:'/support',tenantId:'global',visibility:'shared',audiences:['client','marketplace_client','admin'],surfaces:[...sh],tags:['support','help'],keywords:['contact support','support email','support center'],status:'published',links:[{label:'Open support center',href:'/support'}]}),
r({id:'agreement-active',kind:'agreement',title:'Active growth retainer agreement',summary:'Current scope includes strategy, paid media, SEO reporting, analytics reviews, specialist access, and monthly reporting.',href:'/client/finance?agreement=AGR-2026-001',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:[...cd],tags:['agreement','scope'],keywords:['current scope','active agreement','agreement terms'],status:'active',meta:{pendingApprovals:0},links:[{label:'Open agreement',href:'/client/finance?agreement=AGR-2026-001'}]}),
r({id:'invoice-july',kind:'invoice',title:'Invoice INV-2026-0715',summary:'July retainer invoice is overdue because the client-side purchase order release is still pending.',href:'/client/finance?invoice=INV-2026-0715',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:[...cd],tags:['invoice','billing','overdue'],keywords:['where is my invoice','invoice overdue','billing status'],status:'overdue',overdue:true,meta:{amountDue:125000,daysOverdue:14,overdueReason:'Client-side purchase order release is pending'},links:[{label:'Open invoice',href:'/client/finance?invoice=INV-2026-0715'},{label:'Open finance workspace',href:'/client/finance'}]}),
r({id:'ledger-july',kind:'ledger',title:'Ledger and balance snapshot',summary:'Client-visible balance summary includes outstanding invoice value, applied payments, and next billing milestone.',href:'/client/finance?tab=ledger',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:['client_dashboard','help_panel'],tags:['ledger','balance'],keywords:['ledger balance','current balance','outstanding balance'],status:'current',meta:{outstandingBalance:125000},links:[{label:'Open ledger',href:'/client/finance?tab=ledger'}]}),
r({id:'report-july',kind:'report',title:'Monthly growth report — July',summary:'Includes spend, conversions, CAC trend, SEO momentum, approved deliverables, and executive summary.',href:'/client/finance?report=GROWTH-JULY',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:['client_dashboard','help_panel'],tags:['report','monthly'],keywords:['available reports','monthly report'],status:'published',links:[{label:'Open report',href:'/client/finance?report=GROWTH-JULY'}]}),
r({id:'performance-july',kind:'performance_summary',title:'Performance summary — search and paid social',summary:'Covers conversion efficiency, impression share, landing page quality score, and next-step recommendations.',href:'/client/finance?performance=JULY',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:['client_dashboard','help_panel'],tags:['performance','campaign'],keywords:['performance summaries','campaign summary'],status:'ready',links:[{label:'Open performance summary',href:'/client/finance?performance=JULY'}]}),
r({id:'onboarding-analytics',kind:'onboarding_state',title:'Onboarding state — analytics access handoff',summary:'Onboarding is 80% complete. Final step is GA4 property approval and workspace handoff confirmation.',href:'/client/finance?onboarding=analytics-handoff',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:[...cd],tags:['onboarding','next steps'],keywords:['onboarding state','what next','pending setup'],status:'in_progress',meta:{completionPercent:80,nextStep:'Approve GA4 property access'},links:[{label:'Open onboarding state',href:'/client/finance?onboarding=analytics-handoff'}]}),
r({id:'support-2048',kind:'support_message',title:'Support thread #2048 — asset access',summary:'Open support request awaiting client confirmation for creative asset access and backup billing contact.',href:'/support?thread=2048',tenantId:T,workspaceId:W,brandId:B,visibility:'client',audiences:['client','admin'],surfaces:[...cd],tags:['support','messages'],keywords:['support requests','support messages','help ticket'],status:'awaiting_client',links:[{label:'Open support thread',href:'/support?thread=2048'}]}),
r({id:'proposal-cro',kind:'proposal',title:'Marketplace proposal — CRO sprint',summary:'Proposal is ready for review with scope, timeline, and estimated cost.',href:'/marketplace?proposal=PROP-CRO-001',tenantId:T,workspaceId:W,brandId:B,visibility:'marketplace_client',audiences:['marketplace_client','admin'],surfaces:[...mp],tags:['proposal','marketplace'],keywords:['how proposals work','proposal status','marketplace proposal'],status:'awaiting_approval',meta:{pendingApprovals:1},links:[{label:'Open proposal',href:'/marketplace?proposal=PROP-CRO-001'}]}),
r({id:'request-404',kind:'marketplace_request',title:'Marketplace request #404 — landing page refresh',summary:'Request is in specialist matching with CRO and design specialists being shortlisted.',href:'/marketplace?request=REQ-404',tenantId:T,workspaceId:W,brandId:B,visibility:'marketplace_client',audiences:['marketplace_client','admin'],surfaces:[...mp],tags:['request','specialists'],keywords:['submit request','request status','specialist availability'],status:'matching',links:[{label:'Open request',href:'/marketplace?request=REQ-404'}]}),
r({id:'deliverable-audit',kind:'approved_deliverable',title:'Approved deliverable — landing page audit',summary:'Deliverable package includes audit, CRO roadmap, and implementation checklist.',href:'/marketplace?deliverable=LANDING-AUDIT',tenantId:T,workspaceId:W,brandId:B,visibility:'marketplace_client',audiences:['marketplace_client','admin'],surfaces:['marketplace_surface','help_panel'],tags:['deliverable','approved'],keywords:['approved deliverables','documents available'],status:'approved',links:[{label:'Open deliverable',href:'/marketplace?deliverable=LANDING-AUDIT'}]}),
r({id:'help-specialists',kind:'help_article',title:'Marketplace specialist availability logic',summary:'Specialists are matched by lane, availability, delivery confidence, and active workload.',href:'/marketplace',tenantId:T,workspaceId:W,brandId:B,visibility:'marketplace_client',audiences:['marketplace_client','admin'],surfaces:[...mp],tags:['marketplace','specialists','lanes'],keywords:['specialist availability','service lanes','how to submit requests'],status:'published',links:[{label:'Open marketplace help',href:'/marketplace'}]}),
r({id:'admin-margins',kind:'report',title:'Admin-only margin health snapshot',summary:'Internal commercial margin summary for admin financial review only.',href:'/admin/commercial?tab=margins',tenantId:T,workspaceId:W,brandId:B,visibility:'admin',audiences:['admin'],surfaces:['help_panel'],tags:['internal finance','margin'],keywords:['margin health','admin-only financial'],status:'internal',links:[{label:'Open commercial margins',href:'/admin/commercial?tab=margins'}]}),
r({id:'secret-config',kind:'setting',title:'Internal secret config manifest',summary:'Protected internal settings and secret configuration details.',href:'/admin/config?tab=secret-manifest',tenantId:T,workspaceId:W,brandId:B,visibility:'internal',audiences:['admin'],surfaces:['help_panel'],tags:['secret','config'],keywords:['secret config','internal notes','config details'],status:'locked',links:[{label:'Open admin config',href:'/admin/config?tab=secret-manifest'}]}),
r({id:'other-tenant-invoice',kind:'invoice',title:'Other tenant invoice — must never leak',summary:'Cross-tenant billing artifact that should remain inaccessible.',href:'/client/finance?invoice=INV-OTHER-001',tenantId:O,workspaceId:'workspace_hidden_ops',brandId:'brand_hidden_ops',visibility:'client',audiences:['client','admin'],surfaces:[...cd],tags:['invoice','restricted'],keywords:['other tenant invoice','hidden invoice'],status:'restricted',links:[{label:'Restricted',href:'/client/finance?invoice=INV-OTHER-001'}]}),
]