import type { ApiAccessContext } from '@/lib/auth/api-access'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'
import { googleAccessToken } from '@/lib/integrations/google'

function operational(access:ApiAccessContext){const m=access.membership.metadata||{};const tenantId=typeof m.operationalTenantId==='string'?m.operationalTenantId:null;const workspaceId=typeof m.operationalWorkspaceId==='string'?m.operationalWorkspaceId:null;if(!tenantId)throw new Error('google_ads_tenant_missing');return{tenantId,workspaceId}}
function version(){return process.env.GOOGLE_ADS_API_VERSION||'v25'}
async function headers(tenantId:string){const{accessToken}=await googleAccessToken(tenantId);const h:Record<string,string>={Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json','developer-token':process.env.GOOGLE_ADS_DEVELOPER_TOKEN||''};if(!h['developer-token'])throw new Error('google_ads_developer_token_not_configured');if(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID)h['login-customer-id']=process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID.replace(/-/g,'');return h}
function customer(value:string){const id=value.replace(/\D/g,'');if(!id)throw new Error('google_ads_customer_required');return id}

async function approved(access:ApiAccessContext,approvalId:string,resourceType:string){const ctx=operational(access);const admin=createSupabaseAdminClient();const{data,error}=await admin.from('commercial_approval_requests').select('*').eq('id',approvalId).eq('tenant_id',ctx.tenantId).eq('status','approved').maybeSingle();if(error||!data)throw new Error('approved_request_required');if(data.resource_type&&data.resource_type!==resourceType)throw new Error('approval_resource_mismatch');return data}
async function recordResource(access:ApiAccessContext,input:{customerId:string;resourceType:string;resourceName:string;displayName?:string;metadata?:Record<string,unknown>;write?:boolean}){const ctx=operational(access);const admin=createSupabaseAdminClient();const account=await admin.from('integration_accounts').select('id').eq('tenant_id',ctx.tenantId).eq('provider','google').eq('status','connected').order('created_at',{ascending:false}).limit(1).maybeSingle();const accountId=account.data?.id||null;const{data,error}=await admin.from('provider_resource_links').upsert({tenant_id:ctx.tenantId,workspace_id:ctx.workspaceId,account_id:accountId,provider:'google_ads',resource_type:input.resourceType,external_resource_id:input.resourceName,external_parent_id:input.customerId,display_name:input.displayName||input.resourceName,status:'active',metadata:input.metadata||{},last_read_at:input.write?null:new Date().toISOString(),last_write_at:input.write?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'tenant_id,provider,resource_type,external_resource_id'}).select('*').single();if(error)throw new Error(`google_ads_resource_write_failed:${error.message}`);return data}
async function mutate(tenantId:string,customerId:string,resource:string,body:unknown){const response=await fetch(`https://googleads.googleapis.com/${version()}/customers/${customer(customerId)}/${resource}:mutate`,{method:'POST',headers:await headers(tenantId),body:JSON.stringify(body)});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`google_ads_mutate_failed:${payload?.error?.status||response.status}`);return payload}

export async function createPausedSearchCampaign(access:ApiAccessContext,input:{approvalId:string;customerId:string;name:string;dailyBudgetMicros:number}){await approved(access,input.approvalId,'google_ads_campaign');const ctx=operational(access);const customerId=customer(input.customerId);const micros=Math.max(1_000_000,Math.trunc(input.dailyBudgetMicros));const suffix=Date.now();const budget=await mutate(ctx.tenantId,customerId,'campaignBudgets',{operations:[{create:{name:`${input.name} budget ${suffix}`,amountMicros:String(micros),deliveryMethod:'STANDARD',explicitlyShared:false}}]});const budgetResource=budget?.results?.[0]?.resourceName;if(!budgetResource)throw new Error('google_ads_budget_resource_missing');const campaign=await mutate(ctx.tenantId,customerId,'campaigns',{operations:[{create:{name:input.name,status:'PAUSED',advertisingChannelType:'SEARCH',campaignBudget:budgetResource,maximizeClicks:{},networkSettings:{targetGoogleSearch:true,targetSearchNetwork:true,targetContentNetwork:false,targetPartnerSearchNetwork:false}}}]});const resourceName=campaign?.results?.[0]?.resourceName;if(!resourceName)throw new Error('google_ads_campaign_resource_missing');const link=await recordResource(access,{customerId,resourceType:'campaign',resourceName,displayName:input.name,write:true,metadata:{approvalId:input.approvalId,budgetResource,dailyBudgetMicros:micros,createdStatus:'PAUSED'}});return{resourceName,budgetResource,status:'PAUSED',link}}

export async function updateOrPauseCampaign(access:ApiAccessContext,input:{approvalId:string;customerId:string;resourceName:string;name?:string;pause?:boolean}){await approved(access,input.approvalId,'google_ads_campaign');const ctx=operational(access);const update:any={resourceName:input.resourceName};const fields:string[]=[];if(input.name?.trim()){update.name=input.name.trim();fields.push('name')}if(input.pause!==false){update.status='PAUSED';fields.push('status')}if(!fields.length)throw new Error('google_ads_update_empty');await mutate(ctx.tenantId,input.customerId,'campaigns',{operations:[{update,updateMask:fields.join(',')}]});await recordResource(access,{customerId:customer(input.customerId),resourceType:'campaign',resourceName:input.resourceName,displayName:input.name,write:true,metadata:{approvalId:input.approvalId,lastMutation:fields}});return readCampaign(access,{customerId:input.customerId,resourceName:input.resourceName})}

export async function readCampaign(access:ApiAccessContext,input:{customerId:string;resourceName:string}){const ctx=operational(access);const campaignId=input.resourceName.split('/').pop()?.replace(/\D/g,'');if(!campaignId)throw new Error('google_ads_campaign_resource_invalid');const response=await fetch(`https://googleads.googleapis.com/${version()}/customers/${customer(input.customerId)}/googleAds:search`,{method:'POST',headers:await headers(ctx.tenantId),body:JSON.stringify({query:`SELECT campaign.id, campaign.name, campaign.status, campaign.advertising_channel_type, campaign_budget.amount_micros FROM campaign WHERE campaign.id = ${campaignId} LIMIT 1`})});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`google_ads_read_failed:${payload?.error?.status||response.status}`);const row=payload?.results?.[0]||null;if(row?.campaign?.resourceName)await recordResource(access,{customerId:customer(input.customerId),resourceType:'campaign',resourceName:row.campaign.resourceName,displayName:row.campaign.name,metadata:{status:row.campaign.status},write:false});return row}
